server:
  port: 9003
spring:
  application:
    name: dispatcher-service
  cloud:
    function:
      definition: pack|label #Spring Cloud Function? ??? ?? ??, ??? ??? ???? ?? ??? ?? ?? ??? ??? ????? ???? ??
    stream:
      bindings: #?? ??? ??? ?? ??
        packlabel-in-0: #?? ???
          destination: order-accepted #???? ??? ??? ??? ???? ?? ??(RabbitMQ? ?????)
          group: ${spring.application.name} #??? ??? ?? Consumer ?? (?????? ??? ??)
        packlabel-out-0:  #?? ???
          destination: order-dispatched
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000 # 5s
      request-read-timeout: 5000 # 5s
      fail-fast: false # In production, set to true
      retry:
        max-attempts: 6
        initial-interval: 1000 # 1s
        max-interval: 2000 # 2s
        multiplier: 1.1
  rabbitmq:
    host: localhost
    port: 5672 #AMQP
    username: user
    password: password
    connection-timeout: 5s
  config:
    import: "optional:configserver:"

